module.exports = {
  TALKS: 'TALKS',
  TALK_EVENTS: 'TALK_EVENTS',
  LOGGED_USER: 'LOGGED_USER',
  USERS: 'USERS',
  ADD_TALK: 'ADD_TALK',
  SET_TALKS: 'SET_TALKS',
  DELETE_TALK: 'DELETE_TALK',
  EDIT_TALK: 'EDIT_TALK',
  SET_USER: 'SET_USER',
  UNSET_USER: 'UNSET_USER'
}
